- name: Download kafka
  get_url:
    url: "http://apache.mirrors.tds.net/kafka/{{ base_kafka_version }}/kafka_{{ kafka_version }}.tgz"
    dest: "/root/kafka_{{ kafka_version }}.tgz"
    mode: 0440

- name: Unarchive kafka
  unarchive:
    src: "/root/kafka_{{ kafka_version }}.tgz"
    dest: "/opt"
    creates: "/opt/kafka_{{ kafka_version }}"
    copy: "no"

- name: Create kafka symbolic links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: "/opt/kafka_{{ kafka_version }}"
      dest: "/opt/kafka"
    - src: "/opt/kafka/config"
      dest: "/etc/kafka"

- name: Drop Kafka Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - src: "kafka/kafka-server-start.sh.j2"
      dest: "/opt/kafka_{{ kafka_version }}/bin/kafka-server-start.sh"
      owner: "root"
      group: "root"
      mode: "0775"
    - src: "kafka/kafka.service.j2"
      dest: "/etc/systemd/system/kafka.service"
      owner: "root"
      group: "root"
    - src: "kafka/log4j.properties.j2"
      dest: "/etc/kafka/log4j.properties"
      owner: "kafka"
      group: "kafka"
    - src: "kafka/server.properties.j2"
      dest: "/etc/kafka/server.properties"
      owner: "kafka"
      group: "kafka"
  register: kafka_config

- name: Ensure kafka launches on boot
  service:
    name: "kafka"
    enabled: "yes"

- name: Restart kafka
  service:
    name: "kafka"
    state: "restarted"
  when: kafka_config.changed
